version: '3.8'

services:
  app:
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    command: npm run start:dev
    environment:
      - NODE_ENV=${NODE_ENV}

  migration:
    build:
      context: .
    command: npm run migration:generate
    volumes:
      - .:/usr/src/app
    environment:
      - NODE_ENV=${NODE_ENV}
      - DATABASE_URL=${DATABASE_URL}
    depends_on:
      - db
    networks:
      - app-network
